analysis:
  nbins: 2
  nside: 256
  shift: 1.0,1.0
  vargauss: 0.02825469904152235,0.020759280651486467
  ng_average: 20.00,20.00
  cl_file: ./data/cl.npy
  pixwin: healpix
io:
  datafile: ./data/data_with_pixelazation_and_lpf.h5
  io_dir: ./GKaRMMa_data/test_run/
  maskfile: ./data/mask.npy
  x_init_file: None
mcmc:
  n_burn_in: 200
  n_samples: 200
  step_size: 0.2
  vargauss_training_data_path: ./data/vargauss_training_data.pt
  y_cl_training_data_path: ./data/y_cl_training_data.pt
 
    
