analysis:
  nbins: 2
  nside: 256
  ng_average: 20.00,20.00
  pixwin: healpix
  N_theta: 2 
  theta_fid: 0.3111,0.825,-1,0.049,0.6766,0.9665
  N_bias: 2
  b_fid: 1.0,1.0
io:
  datafile: ./data/data.h5
  io_dir: /iodir
  maskfile: ./data/des_y3/mask_desy3.fits
  x_init_file: None
mcmc:
  n_burn_in: 200
  n_samples: 500
  step_size: 0.2
  vargauss_training_data_path: ./data/vargauss_training_data.pt
  y_cl_training_data_path: ./data/y_cl_training_data.pt

mocks:
    #(Omega_m, S8, w, Omegab, h, ns)
    N_theta: 2
    theta_fid: 0.325,0.8,-1.0,0.05,0.7,0.95
    N_bias: 2
    b_fid: 1.0,1.0
 
    
